name: Pull Requests

on:
  pull_request:
    types:
      - opened

jobs:
  pr_handler:
    name: Pull Request Handler
    permissions:
      contents: read
      pull-requests: write
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Pull Request Handler
        uses: ScoopInstaller/GithubActions@e174c3bef2aeec16a40f2f075cafa167733f0a3e # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
